[package]
name = "linlog"
version = "0.1.0"
edition = "2024"

[dependencies]
chumsky = { version = "0.12.0", features = ["memoization", "pratt"], optional = true }
condtype = "1.3.0"
serde = { version = "1.0.228", features = ["derive"], optional = true }
thiserror = "2.0.17"

[features]
default = ["parse", "serialize"]
parse = ["dep:chumsky"]
serialize = ["dep:serde"]
