# linlog © Fabian Lukas Grubmüller 2026
# Licensed under the EUPL

[package]
name = "linlog"
description = "A linear logic suite for all your needs."
version = "0.1.0"
edition = "2024"
license = "EUPL-1.2"

[dependencies]
chumsky = { version = "0.13.0", features = ["pratt"], optional = true }
foldhash = "0.1.5"
serde = { version = "1.0.228", features = ["derive"], optional = true }
thiserror = "2.0.17"

[features]
default = ["interactive", "parse", "serialize"]
interactive = []
parse = ["dep:chumsky"]
serialize = ["dep:serde"]

[lints]
workspace = true

[dev-dependencies]
serde_json = "1.0.149"
